version: 1
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: paktha-strapi-task
        LoadBalancerInfo:
          ContainerName: strapi
          ContainerPort: 1337
