version: 1
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: PLACEHOLDER_TASK_DEF
        LoadBalancerInfo:
          ContainerName: strapi
          ContainerPort: 1337
